services:
  database:
    image: postgres:15-alpine
    container_name: bookshelf-postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: bookshelf-adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
  api:
    image: ghcr.io/casedev935/bookshelf/api:latest
    container_name: bookshelf-api
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@database:5432/${DB_NAME}?schema=public
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - database

  web:
    image: ghcr.io/casedev935/bookshelf/web:latest
    container_name: bookshelf-web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data:
